再帰的にフォルダ構造を探索するように
traPtitech/localfile-backup-helper pull request #6
Opened 2021-12-23 18:07 UTC by logica0419

フラットなファイル構造以外にも対応しました
オブジェクトの名前はそのままファイルのパスを直でぶちこんでます

2021-12-23 18:11 UTC, logica0419 commented
僕のGCPは無料期間過ぎちゃって課金しないとテストができなくて、traPのGCPで試せるならそちらでテストして欲しいな～という感じです…

2021-12-24 13:37 UTC, sapphi-red requested changes

2021-12-24 13:37 UTC, sapphi-red commented on gcp.go
> +		err = copyFile(bucket, localPath+"/"+filePath, filePath)
```suggestion
		err = copyFile(bucket, filePath, filePath)
```
`filePath`には`localPath`の部分も含まれているのでいらないみたいでした 🖖

2021-12-24 14:05 UTC, logica0419 commented on gcp.go
> +		err = copyFile(bucket, localPath+"/"+filePath, filePath)
なるほどそれは知らなかった
オブジェクト名からのlocalPath部分の削除はいらないですかね？ちょっとめんどそうっちゃめんどそうですけど

2021-12-24 17:57 UTC, logica0419 commented
issue #7 も、テストしにくいと思ったのでついでにやっちゃいました
セマフォの制限ルーティン数を環境変数で設定するかどうかが悩みどこなので、そこ意見もらいたいですね

2021-12-25 12:01 UTC, sapphi-red commented
c1c0f98 は影響が大きいので別のPRにしてほしいです

2021-12-25 12:12 UTC, sapphi-red requested changes

2021-12-25 12:12 UTC, sapphi-red commented on env_var.go
> +	webhookSecret := getEnvWOError("TRAQ_WEBHOOK_SECRET")
どっちも値がある、あるいは、どっちも値がない場合以外をはじくようにしてほしいです :pray:

2021-12-25 12:12 UTC, sapphi-red commented on env_var.go
> +	// 指定された名前の環境変数を取得、空ならばエラーを吐く
エラーではなくて警告なのでそう書き換えておいてほしいです :pray:

2021-12-25 12:12 UTC, sapphi-red commented on env_var.go
> +func getEnvWOError(name string) string {
`wo`はwithoutの略だと思うんですが、`w/o`みたいにスラッシュがないとわかりにくいので、`without`ってするほうがよさそうだと思います
それとwarning出すことに触れるとよさそうです

2021-12-25 12:12 UTC, sapphi-red commented on webhook.go
> +		fmt.Print(mes)
実際には送信されていないことと送信されていない理由、または、仮に送信されていたのであればこの文面であったというような出力にしてほしいです :pray:
今の出力だと何なのかがソースコード読むまでわかりにくいと思うので

2021-12-26 14:20 UTC, logica0419 commented
パパっとやりました
セマフォをUndoしたのでフォースプッシュしました

2021-12-26 14:32 UTC, sapphi-red commented on env_var.go
> +		panic(fmt.Sprintf("Error: env-var \"%s\", \"%s\" empty", idName, secName))
エラー文を`,`じゃなくて`and`と`or`にしてほしいです :pray:

2021-12-26 14:44 UTC, sapphi-red approved these changes
:yosa: :pro: :tada:

2021-12-26 14:44 UTC, merged